import { describe, it, expect } from 'vitest'
import { ThemeInsightSchema, CognitivePatternSchema, ProfileResponseSchema } from '../../schemas/profile'

describe('ThemeInsightSchema', () => {
  it('accepts a valid theme insight', () => {
    /**
     * ThemeInsight objects are generated by the AI profile pipeline and stored
     * as part of the PsychologicalProfile. This tests the happy path where all
     * required fields are present and within valid ranges.
     * Input: theme string, frequency 1-10, description string
     * Expected output: successful parse with unchanged data
     */
    const result = ThemeInsightSchema.safeParse({
      theme: 'work stress',
      frequency: 8,
      description: 'Recurring tension between workload demands and capacity.',
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.theme).toBe('work stress')
      expect(result.data.frequency).toBe(8)
    }
  })

  it('rejects a frequency below 1', () => {
    /**
     * Frequency represents how often a theme appears across journal entries,
     * on a 1–10 scale. A value of 0 is not meaningful and must be rejected
     * to prevent misleading profile data.
     * Input: frequency: 0
     * Expected output: validation failure
     */
    const result = ThemeInsightSchema.safeParse({
      theme: 'anxiety',
      frequency: 0,
      description: 'Some description.',
    })
    expect(result.success).toBe(false)
  })

  it('rejects a frequency above 10', () => {
    /**
     * The frequency scale is capped at 10. Values above this indicate the AI
     * has returned out-of-range data, which should be caught and rejected
     * before it corrupts the profile display.
     * Input: frequency: 11
     * Expected output: validation failure
     */
    const result = ThemeInsightSchema.safeParse({
      theme: 'anxiety',
      frequency: 11,
      description: 'Some description.',
    })
    expect(result.success).toBe(false)
  })
})

describe('CognitivePatternSchema', () => {
  it('accepts a valid CBT cognitive pattern', () => {
    /**
     * CognitivePattern objects are generated by the AI and describe observed
     * psychological patterns using a therapeutic framework. This tests the
     * happy path for a well-formed CBT pattern.
     * Input: valid pattern, CBT framework, description, frequency in range
     * Expected output: successful parse
     */
    const result = CognitivePatternSchema.safeParse({
      pattern: 'catastrophising',
      framework: 'CBT',
      description: 'Tends to assume worst-case outcomes in uncertain situations.',
      frequency: 7,
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.framework).toBe('CBT')
    }
  })

  it('accepts an ACT framework pattern', () => {
    /**
     * The framework field accepts four values: CBT, ACT, DBT, MI. This verifies
     * ACT is accepted as a valid framework so patterns identified under
     * Acceptance and Commitment Therapy are not incorrectly rejected.
     * Input: framework: "ACT"
     * Expected output: successful parse with framework === "ACT"
     */
    const result = CognitivePatternSchema.safeParse({
      pattern: 'experiential avoidance',
      framework: 'ACT',
      description: 'Avoids uncomfortable emotional states rather than processing them.',
      frequency: 5,
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.framework).toBe('ACT')
    }
  })

  it('defaults an unknown framework to "CBT" via .catch()', () => {
    /**
     * The AI occasionally returns framework names outside the four valid options
     * (e.g. "psychodynamic"). The .catch("CBT") fallback ensures the profile
     * is still saved rather than discarded due to an unrecognised framework label.
     * Input: framework: "psychodynamic"
     * Expected output: successful parse with framework defaulted to "CBT"
     */
    const result = CognitivePatternSchema.safeParse({
      pattern: 'some pattern',
      framework: 'psychodynamic',
      description: 'Some description.',
      frequency: 4,
    })
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.framework).toBe('CBT')
    }
  })
})

describe('ProfileResponseSchema', () => {
  const validProfile = {
    summary: 'Josh has shown consistent growth in managing work-related stress over three months.',
    themes: [
      { theme: 'work stress', frequency: 8, description: 'Recurring tension around deadlines.' },
    ],
    cognitivePatterns: [
      { pattern: 'catastrophising', framework: 'CBT', description: 'Worst-case thinking.', frequency: 6 },
    ],
    strengths: ['Strong self-awareness', 'Consistent journaling habit'],
    growthAreas: ['Setting boundaries at work'],
    frameworkInsights: ['CBT techniques around thought challenging would be beneficial'],
    emotionalTrends: ['Mood improving steadily over the period'],
  }

  it('accepts a valid full profile response', () => {
    /**
     * ProfileResponseSchema validates the full JSON object returned by the AI
     * profile generation pipeline before it is stored. This tests all required
     * top-level fields are present and valid.
     * Input: complete profile response object
     * Expected output: successful parse with summary, themes, patterns all intact
     */
    const result = ProfileResponseSchema.safeParse(validProfile)
    expect(result.success).toBe(true)
    if (result.success) {
      expect(result.data.summary).toContain('Josh')
      expect(result.data.themes).toHaveLength(1)
    }
  })

  it('rejects a profile with an empty summary', () => {
    /**
     * The summary field is the primary narrative output of the profile pipeline.
     * An empty string means the AI returned no meaningful content, which should
     * be caught before a blank profile is persisted and displayed to the user.
     * Input: summary: ""
     * Expected output: validation failure
     */
    const result = ProfileResponseSchema.safeParse({ ...validProfile, summary: '' })
    expect(result.success).toBe(false)
  })

  it('rejects a profile with an empty themes array', () => {
    /**
     * The themes array must have at least one entry (min(1)). If the AI returns
     * no themes, it indicates a failure in the analysis and the profile should
     * not be accepted as valid — an empty profile would be misleading.
     * Input: themes: []
     * Expected output: validation failure
     */
    const result = ProfileResponseSchema.safeParse({ ...validProfile, themes: [] })
    expect(result.success).toBe(false)
  })

  it('rejects a profile missing required fields', () => {
    /**
     * The schema requires all top-level fields to be present. Partial responses
     * from the AI (e.g. missing growthAreas) should be rejected so the profile
     * store never holds incomplete data.
     * Input: object missing the growthAreas field
     * Expected output: validation failure
     */
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { growthAreas, ...partial } = validProfile
    const result = ProfileResponseSchema.safeParse(partial)
    expect(result.success).toBe(false)
  })
})
